/************************************************************************//**
 * @file
 * @version Preview
 * @copyright Copyright (c) Microsoft Corporation. All rights reserved.
 * SPDX-License-Identifier: MIT
 * @brief The Embedded Wireless Framework configuration.
 ****************************************************************************/

#ifndef __ewf_config__h__included__
#define __ewf_config__h__included__

#ifdef __cplusplus
extern "C" {
#endif

/* Include the ewf configurations generated by IDE code generator */
#include "ewf_config.h"

#ifdef __cplusplus
}
#endif

#endif /* __ewf_config__h__included__ */
