/************************************************************************//**
 * @file
 * @version Preview
 * @copyright Copyright (c) Microsoft Corporation. All rights reserved.
 * SPDX-License-Identifier: MIT
 * @details
 * The Embedded Wireless Framework example configuration.
 ****************************************************************************/


#ifndef __ewf_example_conf__h__included__
#define __ewf_example_conf__h__included__

#ifdef __cplusplus
extern "C" {
#endif

/* Include the ewf example configurations generated by IDE code generator */
#include "ewf_example_config.h"

#ifdef __cplusplus
}
#endif

#endif /* __ewf_example_conf__h__included__ */
