/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define FLEXCOMM0_PERIPHERAL ((USART_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define FLEXCOMM0_CLOCK_SOURCE 12000000UL
/* Rx transfer buffer size. */
#define FLEXCOMM0_RX_BUFFER_SIZE 10
/* Rx transfer buffer size. */
#define FLEXCOMM0_TX_BUFFER_SIZE 10
/* Definition of peripheral ID */
#define FLEXCOMM2_PERIPHERAL ((USART_Type *)FLEXCOMM2)
/* Definition of the clock source frequency */
#define FLEXCOMM2_CLOCK_SOURCE 12000000UL
/* Rx transfer buffer size. */
#define FLEXCOMM2_RX_BUFFER_SIZE 10
/* Rx transfer buffer size. */
#define FLEXCOMM2_TX_BUFFER_SIZE 10

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const usart_config_t FLEXCOMM0_config;
extern usart_handle_t FLEXCOMM0_handle;
extern uint8_t FLEXCOMM0_rxBuffer[FLEXCOMM0_RX_BUFFER_SIZE];
extern const usart_transfer_t FLEXCOMM0_rxTransfer;
extern uint8_t FLEXCOMM0_txBuffer[FLEXCOMM0_TX_BUFFER_SIZE];
extern const usart_transfer_t FLEXCOMM0_txTransfer;
extern const usart_config_t FLEXCOMM2_config;
extern usart_handle_t FLEXCOMM2_handle;
extern uint8_t FLEXCOMM2_rxBuffer[FLEXCOMM2_RX_BUFFER_SIZE];
extern const usart_transfer_t FLEXCOMM2_rxTransfer;
extern uint8_t FLEXCOMM2_txBuffer[FLEXCOMM2_TX_BUFFER_SIZE];
extern const usart_transfer_t FLEXCOMM2_txTransfer;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
