################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_3des.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_aes.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_des.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_hmac_md5.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_hmac_sha.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_md5.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_prf.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_rsa.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_sha.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_rng_self_test.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_table_self_test.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_allocate_handshake_packet.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_handshake.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_protocol_version_override.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_ecc_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_hash_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_packet_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_clienthello.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_handshake_header.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_header.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_helloverifyrequest.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_psk_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_receive_callback.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_retransmit.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_retransmit_queue_flush.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_clienthello.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_handshake_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_helloverifyrequest.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_serverhello.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_create.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_delete.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_ecc_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_handshake.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_notify_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_protocol_version_override.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_psk_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_session_send.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_stop.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_configure.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_disable.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_cache.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_client_info_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_create.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_delete.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_end.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_receive.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_reset.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_send.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_check.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_update.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_verify_mac.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_module_hash_compute.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_client_handshake.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_crypto_init.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_finished_hash_generate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_generate_keys.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_server_handshake.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_session_keys_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_transcript_hash_save.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_active_certificate_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_allocate_handshake_packet.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_check_protocol_version.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ciphersuite_lookup.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_client_handshake.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_client_psk_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ecc_generate_keys.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ecc_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_find_curve_method.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_finished_hash_generate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_generate_keys.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_generate_premaster_secret.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_init.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_update.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_process.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_hash_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_key_material_init.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_map_error_to_alert.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_metadata_size_calculate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_newest_supported_version.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_packet_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_packet_release.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_certificate_request.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_certificate_verify.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_changecipherspec.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_client_key_exchange.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_clienthello.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_clienthello_extensions.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_encrypted_extensions.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_finished.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_handshake_header.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_header.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_newsessionticket.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_remote_certificate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_server_key_exchange.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_serverhello.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_serverhello_extensions.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_protocol_version_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_binder_generate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_identity_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_calculate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_update.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_payload_decrypt.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_payload_encrypt.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_buffer_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free_all.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_verify.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_alert.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate_request.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate_verify.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_changecipherspec.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_client_key_exchange.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_clienthello.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_clienthello_extensions.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_encrypted_extensions.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_finished.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_handshake_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_hellorequest.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_newsessionticket.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_record.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_server_key_exchange.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_serverhello.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_serverhello_extensions.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_handshake.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_alert_value_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_certificate_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_disable.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_enable.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_create.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_create_ext.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_delete.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_end.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_iv_size_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_keys_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_packet_buffer_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_protocol_version_override.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_receive.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_receive_records.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_reset.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_send.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_server_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_time_function_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_x509_client_verify_configure.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_shutdown.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_verify_mac.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_asn1_tlv_block_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_chain_verify.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_revocation_list_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_verify.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_common_name_dns_check.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_crl_revocation_check.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_crl_verify.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_compare.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_dns_name_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_ec_private_key_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_expiration_check.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_extended_key_usage_extension_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_extension_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_find_certificate_methods.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_find_curve_method.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_free_certificate_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_key_usage_extension_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_local_certificate_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_local_device_certificate_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_oid_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_pkcs1_rsa_private_key_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_pkcs7_decode.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_remote_endpoint_certificate_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_subject_alt_names_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_wildcard_compare.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_client_protocol_version_override.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_client_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_ecc_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_packet_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_psk_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_create.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_delete.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_ecc_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_notify_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_protocol_version_override.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_psk_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_session_send.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_stop.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_configure.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_disable.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_client_info_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_create.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_delete.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_end.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_receive.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_reset.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_send.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_active_certificate_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_client_psk_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_metadata_size_calculate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_packet_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_psk_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_buffer_allocate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_free_all.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_alert_value_get.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_certificate_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_disable.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_enable.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_create.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_delete.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_end.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_packet_buffer_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_protocol_version_override.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_receive.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_reset.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_send.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_server_callback_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_start.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_time_function_set.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_x509_client_verify_configure.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_add.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_remove.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_certificate_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_common_name_dns_check.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_crl_revocation_check.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_dns_name_initialize.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_extended_key_usage_extension_parse.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_extension_find.c \
../ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_key_usage_extension_parse.c 

C_DEPS += \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_3des.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_aes.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_des.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_hmac_md5.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_hmac_sha.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_md5.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_prf.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_rsa.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_sha.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_rng_self_test.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_table_self_test.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_allocate_handshake_packet.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_handshake.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_protocol_version_override.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_ecc_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_hash_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_packet_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_clienthello.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_handshake_header.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_header.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_helloverifyrequest.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_psk_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_receive_callback.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_retransmit.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_retransmit_queue_flush.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_clienthello.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_handshake_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_helloverifyrequest.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_serverhello.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_create.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_delete.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_ecc_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_handshake.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_notify_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_protocol_version_override.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_psk_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_session_send.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_stop.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_configure.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_disable.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_cache.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_client_info_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_create.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_delete.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_end.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_receive.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_reset.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_send.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_check.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_update.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_verify_mac.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_module_hash_compute.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_client_handshake.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_crypto_init.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_finished_hash_generate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_generate_keys.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_server_handshake.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_session_keys_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_transcript_hash_save.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_active_certificate_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_allocate_handshake_packet.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_check_protocol_version.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ciphersuite_lookup.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_client_handshake.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_client_psk_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ecc_generate_keys.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ecc_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_find_curve_method.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_finished_hash_generate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_generate_keys.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_generate_premaster_secret.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_init.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_update.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_process.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_hash_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_key_material_init.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_map_error_to_alert.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_metadata_size_calculate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_newest_supported_version.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_packet_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_packet_release.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_certificate_request.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_certificate_verify.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_changecipherspec.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_client_key_exchange.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_clienthello.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_clienthello_extensions.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_encrypted_extensions.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_finished.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_handshake_header.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_header.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_newsessionticket.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_remote_certificate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_server_key_exchange.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_serverhello.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_serverhello_extensions.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_protocol_version_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_binder_generate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_identity_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_calculate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_update.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_payload_decrypt.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_payload_encrypt.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_buffer_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free_all.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_verify.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_alert.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate_request.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate_verify.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_changecipherspec.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_client_key_exchange.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_clienthello.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_clienthello_extensions.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_encrypted_extensions.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_finished.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_handshake_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_hellorequest.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_newsessionticket.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_record.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_server_key_exchange.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_serverhello.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_serverhello_extensions.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_handshake.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_alert_value_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_certificate_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_disable.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_enable.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_create.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_create_ext.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_delete.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_end.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_iv_size_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_keys_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_packet_buffer_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_protocol_version_override.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_receive.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_receive_records.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_reset.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_send.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_server_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_time_function_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_x509_client_verify_configure.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_shutdown.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_verify_mac.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_asn1_tlv_block_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_chain_verify.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_revocation_list_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_verify.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_common_name_dns_check.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_crl_revocation_check.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_crl_verify.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_compare.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_dns_name_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_ec_private_key_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_expiration_check.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_extended_key_usage_extension_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_extension_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_find_certificate_methods.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_find_curve_method.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_free_certificate_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_key_usage_extension_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_local_certificate_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_local_device_certificate_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_oid_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_pkcs1_rsa_private_key_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_pkcs7_decode.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_remote_endpoint_certificate_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_subject_alt_names_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_wildcard_compare.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_client_protocol_version_override.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_client_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_ecc_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_packet_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_psk_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_create.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_delete.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_ecc_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_notify_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_protocol_version_override.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_psk_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_session_send.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_stop.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_configure.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_disable.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_client_info_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_create.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_delete.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_end.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_receive.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_reset.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_send.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_active_certificate_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_client_psk_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_metadata_size_calculate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_packet_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_psk_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_buffer_allocate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_free_all.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_alert_value_get.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_certificate_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_disable.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_enable.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_create.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_delete.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_end.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_packet_buffer_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_protocol_version_override.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_receive.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_reset.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_send.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_server_callback_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_start.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_time_function_set.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_x509_client_verify_configure.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_add.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_remove.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_certificate_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_common_name_dns_check.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_crl_revocation_check.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_dns_name_initialize.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_extended_key_usage_extension_parse.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_extension_find.d \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_key_usage_extension_parse.d 

OBJS += \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_3des.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_aes.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_des.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_hmac_md5.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_hmac_sha.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_md5.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_prf.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_rsa.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_method_self_test_sha.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_rng_self_test.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_crypto_table_self_test.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_allocate_handshake_packet.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_handshake.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_protocol_version_override.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_client_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_ecc_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_hash_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_packet_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_clienthello.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_handshake_header.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_header.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_helloverifyrequest.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_process_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_psk_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_receive_callback.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_retransmit.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_retransmit_queue_flush.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_clienthello.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_handshake_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_helloverifyrequest.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_send_serverhello.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_create.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_delete.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_ecc_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_handshake.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_notify_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_protocol_version_override.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_psk_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_session_send.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_stop.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_configure.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_disable.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_cache.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_client_info_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_create.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_delete.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_end.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_receive.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_reset.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_send.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_check.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_update.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_dtls_verify_mac.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_module_hash_compute.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_client_handshake.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_crypto_init.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_finished_hash_generate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_generate_keys.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_server_handshake.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_session_keys_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_1_3_transcript_hash_save.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_active_certificate_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_allocate_handshake_packet.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_check_protocol_version.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ciphersuite_lookup.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_client_handshake.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_client_psk_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ecc_generate_keys.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_ecc_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_find_curve_method.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_finished_hash_generate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_generate_keys.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_generate_premaster_secret.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_init.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_update.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_handshake_process.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_hash_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_key_material_init.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_local_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_map_error_to_alert.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_metadata_size_calculate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_newest_supported_version.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_packet_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_packet_release.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_certificate_request.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_certificate_verify.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_changecipherspec.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_client_key_exchange.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_clienthello.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_clienthello_extensions.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_encrypted_extensions.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_finished.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_handshake_header.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_header.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_newsessionticket.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_remote_certificate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_server_key_exchange.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_serverhello.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_process_serverhello_extensions.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_protocol_version_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_binder_generate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_psk_identity_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_calculate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_hash_update.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_payload_decrypt.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_record_payload_encrypt.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_buffer_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free_all.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_verify.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_alert.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate_request.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_certificate_verify.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_changecipherspec.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_client_key_exchange.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_clienthello.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_clienthello_extensions.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_encrypted_extensions.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_finished.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_handshake_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_hellorequest.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_newsessionticket.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_record.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_server_key_exchange.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_serverhello.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_send_serverhello_extensions.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_server_handshake.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_alert_value_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_certificate_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_disable.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_enable.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_create.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_create_ext.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_delete.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_end.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_iv_size_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_keys_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_packet_buffer_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_protocol_version_override.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_receive.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_receive_records.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_reset.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_send.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_server_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_time_function_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_session_x509_client_verify_configure.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_shutdown.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_tls_verify_mac.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_asn1_tlv_block_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_chain_verify.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_list_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_revocation_list_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_certificate_verify.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_common_name_dns_check.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_crl_revocation_check.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_crl_verify.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_compare.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_dns_name_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_ec_private_key_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_expiration_check.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_extended_key_usage_extension_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_extension_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_find_certificate_methods.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_find_curve_method.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_free_certificate_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_key_usage_extension_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_local_certificate_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_local_device_certificate_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_oid_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_pkcs1_rsa_private_key_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_pkcs7_decode.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_remote_endpoint_certificate_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_store_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_subject_alt_names_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nx_secure_x509_wildcard_compare.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_client_protocol_version_override.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_client_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_ecc_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_packet_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_psk_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_create.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_delete.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_ecc_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_notify_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_protocol_version_override.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_psk_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_session_send.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_stop.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_configure.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_disable.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_client_info_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_create.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_delete.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_end.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_receive.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_reset.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_send.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_active_certificate_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_client_psk_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_metadata_size_calculate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_packet_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_psk_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_buffer_allocate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_free_all.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_alert_value_get.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_certificate_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_disable.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_enable.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_create.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_delete.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_end.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_packet_buffer_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_protocol_version_override.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_receive.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_reset.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_send.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_server_callback_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_start.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_time_function_set.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_session_x509_client_verify_configure.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_add.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_remove.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_certificate_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_common_name_dns_check.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_crl_revocation_check.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_dns_name_initialize.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_extended_key_usage_extension_parse.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_extension_find.o \
./ra/microsoft/azure-rtos/netxduo/nx_secure/src/nxe_secure_x509_key_usage_extension_parse.o 

SREC += \
ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014.srec 

MAP += \
ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014.map 


# Each subdirectory must supply rules for building sources it contributes
ra/microsoft/azure-rtos/netxduo/nx_secure/src/%.o: ../ra/microsoft/azure-rtos/netxduo/nx_secure/src/%.c
	$(file > $@.in,-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal  -g -D_RA_CORE=CM33 -D_RENESAS_RA_ -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/src" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/inc/api" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/inc/instances" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/rm_threadx_port" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/threadx/common/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/arm/CMSIS_5/CMSIS/Core/Include" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra_gen" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra_cfg/fsp_cfg/bsp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra_cfg/fsp_cfg" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra_cfg/fsp_cfg/azure/tx" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/private/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/public/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/r_sce/common" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/r_sce" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/rm_netxduo_ether" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/rm_netx_secure_crypto/inc/crypto_common" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/fsp/src/rm_netx_secure_crypto/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/pop3" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/snmp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/nat" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/mqtt" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/ftp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/tftp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/sntp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/smtp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/web" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/auto_ip" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/telnet" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/dns" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/dhcp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/http" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/common/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/ports/cortex_m4" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/cloud" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/inc/configs/RTOS_BASE" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/crypto_libraries/src" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/crypto_libraries/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra/microsoft/azure-rtos/netxduo/nx_secure/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra_cfg/fsp_cfg/middleware" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_ryz014/ra_cfg/fsp_cfg/azure/nxd" -I"C:/comms_framework/src" -I"C:/comms_framework/src/examples" -I"C:/comms_framework/src/templates" -I"C:/comms_framework/src/test" -std=c99 -Wno-aggregate-return -w -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

