################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_allocate.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_cleanup.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_block_release.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_allocate.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_cleanup.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_search.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_byte_release.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_cleanup.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_high_level.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_enter.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_setup.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_cleanup.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_priority_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_put.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_cleanup.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_flush.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_front_send.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_receive.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_send.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_queue_send_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_ceiling_put.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_cleanup.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_entry_exit_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_identify.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_preemption_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_priority_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_relinquish.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_reset.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_resume.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_shell_entry.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_sleep.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_analyze.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_handler.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_suspend.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_preempt_check.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_resume.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_suspend.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_terminate.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_timeout.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_thread_wait_abort.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_time_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_time_set.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_activate.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_deactivate.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_expiration_process.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_system_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_system_activate.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_system_deactivate.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_timer_thread_entry.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_buffer_full_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_disable.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_enable.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_event_filter.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_event_unfilter.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_initialize.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_interrupt_control.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_enter_insert.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_exit_insert.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_object_register.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_object_unregister.c \
../ra/microsoft/azure-rtos/threadx/common/src/tx_trace_user_event_insert.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_block_allocate.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_block_release.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_byte_allocate.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_byte_release.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_put.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_flush.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_front_send.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_receive.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_send.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_queue_send_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_ceiling_put.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_prioritize.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_entry_exit_notify.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_info_get.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_preemption_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_priority_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_relinquish.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_reset.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_resume.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_suspend.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_terminate.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_time_slice_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_thread_wait_abort.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_timer_activate.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_timer_change.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_timer_create.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_timer_deactivate.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_timer_delete.c \
../ra/microsoft/azure-rtos/threadx/common/src/txe_timer_info_get.c 

C_DEPS += \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_allocate.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_cleanup.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_release.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_allocate.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_cleanup.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_search.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_release.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_cleanup.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_high_level.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_enter.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_setup.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_cleanup.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_priority_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_put.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_cleanup.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_flush.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_front_send.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_receive.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_send.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_send_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_ceiling_put.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_cleanup.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_entry_exit_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_identify.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_preemption_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_priority_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_relinquish.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_reset.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_resume.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_shell_entry.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_sleep.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_analyze.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_handler.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_suspend.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_preempt_check.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_resume.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_suspend.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_terminate.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_timeout.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_wait_abort.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_time_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_time_set.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_activate.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_deactivate.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_expiration_process.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_system_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_system_activate.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_system_deactivate.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_thread_entry.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_buffer_full_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_disable.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_enable.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_event_filter.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_event_unfilter.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_initialize.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_interrupt_control.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_enter_insert.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_exit_insert.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_object_register.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_object_unregister.d \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_user_event_insert.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_allocate.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_release.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_allocate.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_release.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_put.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_flush.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_front_send.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_receive.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_send.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_send_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_ceiling_put.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_prioritize.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_entry_exit_notify.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_info_get.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_preemption_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_priority_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_relinquish.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_reset.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_resume.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_suspend.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_terminate.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_time_slice_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_wait_abort.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_activate.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_change.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_create.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_deactivate.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_delete.d \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_info_get.d 

OBJS += \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_allocate.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_cleanup.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_pool_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_block_release.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_allocate.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_cleanup.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_search.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_byte_release.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_cleanup.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_high_level.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_enter.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_setup.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_cleanup.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_priority_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_mutex_put.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_cleanup.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_flush.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_front_send.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_receive.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_send.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_queue_send_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_ceiling_put.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_cleanup.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_entry_exit_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_identify.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_preemption_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_priority_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_relinquish.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_reset.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_resume.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_shell_entry.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_sleep.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_analyze.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_handler.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_suspend.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_preempt_check.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_resume.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_system_suspend.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_terminate.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_timeout.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_thread_wait_abort.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_time_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_time_set.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_activate.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_deactivate.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_expiration_process.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_system_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_system_activate.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_system_deactivate.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_timer_thread_entry.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_buffer_full_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_disable.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_enable.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_event_filter.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_event_unfilter.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_initialize.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_interrupt_control.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_enter_insert.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_exit_insert.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_object_register.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_object_unregister.o \
./ra/microsoft/azure-rtos/threadx/common/src/tx_trace_user_event_insert.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_allocate.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_pool_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_block_release.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_allocate.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_byte_release.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_mutex_put.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_flush.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_front_send.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_receive.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_send.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_queue_send_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_ceiling_put.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_prioritize.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_entry_exit_notify.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_info_get.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_preemption_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_priority_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_relinquish.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_reset.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_resume.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_suspend.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_terminate.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_time_slice_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_thread_wait_abort.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_activate.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_change.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_create.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_deactivate.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_delete.o \
./ra/microsoft/azure-rtos/threadx/common/src/txe_timer_info_get.o 

SREC += \
ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014.srec 

MAP += \
ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014.map 


# Each subdirectory must supply rules for building sources it contributes
ra/microsoft/azure-rtos/threadx/common/src/%.o: ../ra/microsoft/azure-rtos/threadx/common/src/%.c
	$(file > $@.in,-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal  -g -D_RA_CORE=CM33 -D_RENESAS_RA_ -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/src" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/inc/api" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/inc/instances" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/rm_threadx_port" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/threadx/common/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/arm/CMSIS_5/CMSIS/Core/Include" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra_gen" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra_cfg/fsp_cfg/bsp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra_cfg/fsp_cfg" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra_cfg/fsp_cfg/azure/tx" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/private/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/public/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/r_sce/common" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/r_sce" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/rm_netxduo_ether" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/rm_netx_secure_crypto/inc/crypto_common" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/fsp/src/rm_netx_secure_crypto/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/pop3" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/snmp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/nat" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/mqtt" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/ftp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/tftp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/sntp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/smtp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/web" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/auto_ip" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/telnet" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/dns" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/dhcp" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/http" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/common/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/ports/cortex_m4" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/cloud" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/inc/configs/RTOS_BASE" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/crypto_libraries/src" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/crypto_libraries/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra/microsoft/azure-rtos/netxduo/nx_secure/inc" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra_cfg/fsp_cfg/middleware" -I"C:/comms_framework/examples/EK-RA6M4/ewf_netx_duo_azure_iot_embedded_sdk_pnp_temperature_controller_ryz014/ra_cfg/fsp_cfg/azure/nxd" -I"C:/comms_framework/src" -I"C:/comms_framework/src/examples" -I"C:/comms_framework/src/templates" -I"C:/comms_framework/src/test" -std=c99 -Wno-aggregate-return -w -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

